name: Generate GitHub Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aebonlee/github-contribution-grid-snake@v1
        with:
          github_user_name: 'KimTeaKwan'
          gif_out_path: 'github-contribution-grid-snake.gif'
          svg_out_path: 'github-contribution-grid-snake.svg'